###############################################################################
# Always coverage binary
BINARY=coverage

################################################################################
# Library configuration
OPENCM3_DIR = ../libopencm3
LDSCRIPT =
PREFIX = x86_64-linux-gnu

################################################################################
# Compiler arguments

LIBNAME		= opencm3_stm32f4
DEFS		= -DSTM32F4

FP_FLAGS	=
ARCH_FLAGS	=

include ../Makefile.rules
